name: Karnul Bleed CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send Initiation Message
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=html" \
        -d text="CI Build [${GITHUB_ACTION}] Initiated at $(TZ=Asia/Kolkata date)"
    - uses: actions/checkout@v1
    - name: Bleed Karnul
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        export CROSS_COMPILE=${PWD}/aarch64-linux-android-4.9/bin/aarch64-linux-android-
        export KBUILD_BUILD_USER="udit"
        export ARCH=arm64
        export CROSS_COMPILE_ARM32=${PWD}/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
        export SUBARCH=arm64
        export DTC_EXT=dtc
        chmod a+x /home/runner/work/crimson/crimson/scripts/dtc/bin/dtc
        PATH="clang/bin:aarch64-linux-android-4.9/bin:aarch64-linux-android-4.9/bin:/home/runner/work/crimson/crimson/scripts/dtc/bin:${PATH}"
        mkdir clang
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/39e7c63aa6239ae92d63913c82bbe1e9e44b4013/clang-r370808.tar.gz
        tar -C clang -xvzf clang-r*.tar.gz
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/
        make -j12 O=out vendor/violet-perf_defconfig
        make -j12 O=out \
                CROSS_COMPILE=$CROSS_COMPILE \
                CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 \
                CC=${PWD}/clang/bin/clang \
                CLANG_TRIPLE=aarch64-linux-gnu- Image.gz-dtb 2>&1 | tee error.log
        if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
          cp out/arch/arm64/boot/Image.gz-dtb flasher/Image.gz-dtb
          cd flasher
          zip -r9 "CrimsonKernel-KarnulCI.zip" * -x .git README.md LICENSE
          curl --progress-bar -F document=@"CrimsonKernel-KarnulCI.zip" "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument" \
         -F chat_id="${CHAT_ID}"  \
         -F "disable_web_page_preview=true" \
         -F "parse_mode=html" \
         -F caption="Build finished at: $(TZ=Asia/Kolkata date) | DTBO-less zip attached" 
        else
          cat error.log | grep -i -A3 error > bleed_error.txt
          curl --progress-bar -F document=@"bleed_error.txt" "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument" \
         -F chat_id="${CHAT_ID}"  \
         -F "disable_web_page_preview=true" \
         -F "parse_mode=html" \
         -F caption="Build failed at: $(TZ=Asia/Kolkata date) | Trimmed error log attached" 
        fi
    - uses: actions/upload-artifact@v1.0.0
      name: Artifact-ify Bleed
      with:
        name: CIKarnulBleed
        path: CrimsonKernel-KarnulCI.zip
