name: Karnul Bleed CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bleed Karnul
      run: |
        pwd
        whoami
        ls
        awk -F: '{ print $1 }' /etc/passwd
        export CROSS_COMPILE=${PWD}/aarch64-linux-android-4.9/bin/aarch64-linux-android-
        export KBUILD_BUILD_USER="udit"
        export ARCH=arm64
        export CROSS_COMPILE_ARM32=${PWD}/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
        export SUBARCH=arm64
        export DTC_EXT=dtc
        PATH="clang/bin:aarch64-linux-android-4.9/bin:aarch64-linux-android-4.9/bin:scripts/dtc/bin:${PATH}"
        mkdir clang
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/39e7c63aa6239ae92d63913c82bbe1e9e44b4013/clang-r370808.tar.gz
        tar -C clang -xvzf clang-r*.tar.gz
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/
        make -j12 O=out vendor/violet-perf_defconfig
        make -j12 O=out \
                CROSS_COMPILE=$CROSS_COMPILE \
                CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 \
                CC=${PWD}/clang/bin/clang \
                CLANG_TRIPLE=aarch64-linux-gnu- Image.gz-dtb 2>&1 | tee error.log
        cp out/arch/arm64/boot/Image.gz-dtb flasher/Image.gz-dtb
        zip -r9 "CrimsonKernel-KarnulCI.zip" flasher/* -x .git README.md
    - uses: actions/upload-artifact@v1.0.0
      name: Artifact-ify Bleed
      with:
        name: CIKarnulBleed
        path: CrimsonKernel-KarnulCI.zip
    
      
